import type { RoleDefinition, RoleId } from "./types";

// Navigation is capped at 7 top-level groups per role (spec §3).
export const ROLES: Record<RoleId, RoleDefinition> = {
  teacher: {
    id: "teacher",
    label: "Teacher",
    description: "Complete today's teaching work quickly",
    home: "/teacher",
    nav: [
      { key: "home", label: "Home", icon: "Home", to: "/teacher" },
      { key: "classes", label: "My Classes", icon: "Users", to: "/teacher/classes" },
      { key: "attendance", label: "Attendance", icon: "CalendarCheck", to: "/teacher/attendance", permission: "attendance.mark" },
      { key: "learning", label: "Learning", icon: "BookOpen", to: "/teacher/learning" },
      { key: "assessments", label: "Assessments", icon: "ClipboardList", to: "/teacher/assessments" },
      { key: "messages", label: "Messages", icon: "MessageSquare", to: "/teacher/messages" },
      { key: "more", label: "More", icon: "LayoutGrid", to: "/teacher/more" },
    ],
  },
  student: {
    id: "student",
    label: "Student",
    description: "Show what to learn next",
    home: "/student",
    nav: [
      { key: "home", label: "Home", icon: "Home", to: "/student" },
      { key: "learn", label: "Learn", icon: "BookOpen", to: "/student/learn" },
      { key: "tasks", label: "Tasks", icon: "ClipboardList", to: "/student/tasks" },
      { key: "timetable", label: "Timetable", icon: "CalendarDays", to: "/student/timetable" },
      { key: "results", label: "Results", icon: "Award", to: "/student/results" },
      { key: "messages", label: "Messages", icon: "MessageSquare", to: "/student/messages" },
    ],
  },
  parent: {
    id: "parent",
    label: "Parent",
    description: "Show urgent child and family actions",
    home: "/parent",
    nav: [
      { key: "home", label: "Home", icon: "Home", to: "/parent" },
      { key: "child", label: "Child", icon: "Baby", to: "/parent/child" },
      { key: "attendance", label: "Attendance", icon: "CalendarCheck", to: "/parent/attendance" },
      { key: "learning", label: "Learning", icon: "BookOpen", to: "/parent/learning" },
      { key: "fees", label: "Fees", icon: "Wallet", to: "/parent/fees" },
      { key: "messages", label: "Messages", icon: "MessageSquare", to: "/parent/messages" },
    ],
  },
  admin: {
    id: "admin",
    label: "School Admin",
    description: "Guide setup and operations",
    home: "/admin",
    nav: [
      { key: "home", label: "Home", icon: "Home", to: "/admin", permission: "admin.dashboard.view" },
      { key: "people", label: "People", icon: "Users", to: "/admin/people" },
      { key: "admissions", label: "Admissions", icon: "ClipboardCheck", to: "/admissions", permission: "admissions.enquiries.manage" },
      { key: "academics", label: "Academics", icon: "GraduationCap", to: "/admin/academics" },
      { key: "exams", label: "Exams", icon: "FileText", to: "/exams", permission: "exams.view" },
      { key: "operations", label: "Operations", icon: "Settings2", to: "/admin/operations" },
      { key: "communication", label: "Communication", icon: "Megaphone", to: "/admin/communication" },
      { key: "reports", label: "Reports", icon: "BarChart3", to: "/admin/reports" },
      { key: "settings", label: "Settings", icon: "Settings", to: "/admin/settings" },
    ],
  },
  principal: {
    id: "principal",
    label: "Principal",
    description: "Show school health, exceptions and approvals",
    home: "/principal",
    nav: [
      { key: "home", label: "Home", icon: "Home", to: "/principal" },
      { key: "academics", label: "Academics", icon: "GraduationCap", to: "/principal/academics" },
      { key: "exams", label: "Exams", icon: "FileText", to: "/exams", permission: "exams.view" },
      { key: "students", label: "Students", icon: "Users", to: "/principal/students" },
      { key: "staff", label: "Staff", icon: "UserCog", to: "/principal/staff" },
      { key: "finance", label: "Finance", icon: "Wallet", to: "/principal/finance" },
      { key: "reports", label: "Reports", icon: "BarChart3", to: "/principal/reports" },
      { key: "approvals", label: "Approvals", icon: "CheckCircle2", to: "/principal/approvals" },
    ],
  },
  accountant: {
    id: "accountant",
    label: "Accountant",
    description: "Manage collections and exceptions",
    home: "/accountant",
    nav: [
      { key: "home", label: "Home", icon: "Home", to: "/accountant" },
      { key: "fees", label: "Fees", icon: "ReceiptText", to: "/accountant/fees" },
      { key: "payments", label: "Payments", icon: "Wallet", to: "/accountant/payments", permission: "payments.collect" },
      { key: "reconciliation", label: "Reconciliation", icon: "GitCompareArrows", to: "/accountant/reconciliation" },
      { key: "reports", label: "Reports", icon: "BarChart3", to: "/accountant/reports" },
      { key: "settings", label: "Settings", icon: "Settings", to: "/accountant/settings" },
    ],
  },
  platform: {
    id: "platform",
    label: "Platform Admin",
    description: "Manage tenants and platform safely",
    home: "/platform",
    nav: [
      { key: "home", label: "Home", icon: "Home", to: "/platform" },
      { key: "schools", label: "Schools", icon: "Building2", to: "/platform/schools" },
      { key: "plans", label: "Plans", icon: "Package", to: "/platform/plans" },
      { key: "plugins", label: "Plugins", icon: "Plug", to: "/platform/plugins" },
      { key: "operations", label: "Operations", icon: "Activity", to: "/platform/operations" },
      { key: "support", label: "Support", icon: "LifeBuoy", to: "/platform/support" },
      { key: "reports", label: "Reports", icon: "BarChart3", to: "/platform/reports" },
      { key: "settings", label: "Settings", icon: "Settings", to: "/platform/settings" },
    ],
  },
};

export const ROLE_ORDER: RoleId[] = [
  "teacher",
  "student",
  "parent",
  "admin",
  "principal",
  "accountant",
  "platform",
];
